<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%user_temp}}`.
 */
class m250507_125730_create_user_temp_table extends Migration
{
    private $tableName = 'user_temp';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $createdBy = 'system';
        
        if (!YII_ENV_DEV) {
            echo 'Skipping migration/fresh for non-dev environment.\n';
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'user_id' => $this->integer()->notNull(),
            'username' => $this->string(50)->notNull(),
            'name' => $this->string(50)->notNull(),
            'auth_key' => $this->string(255),
            'session_id' => $this->string(50),
            'permission' => $this->json(),
            'role' => $this->json(),
            'superadmin' => $this->boolean()->notNull()->defaultValue(false),
            'admin' => $this->boolean()->notNull()->defaultValue(false),
            'expired_session_id' => $this->timestamp(),
            'status' => $this->boolean()->notNull()->defaultValue(false),
            'cr_id' => $this->integer()
        ]);
    }

    public function safeDown()
    {
        if (!YII_ENV_DEV) {
            echo "Skipping migration/fresh for non-dev environment.\n";
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
