<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%maintenance}}`.
 */
class m250507_122802_create_maintenance_table extends Migration
{
    private $tableName = 'maintenance';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $createdBy = 'system';
        
        if (!YII_ENV_DEV) {
            echo 'Skipping migration/fresh for non-dev environment.\n';
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'status' => $this->smallInteger()->notNull()->defaultValue(0),
            'message' => $this->text(),
        ]);
    }

    public function safeDown()
    {
        if (!YII_ENV_DEV) {
            echo "Skipping migration/fresh for non-dev environment.\n";
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
