<?php

use yii\db\Migration;
// use MongoDB\Client;

/**
 * Handles the creation of table `{{%product_rating}}`.
 */
class m251128_165000_create_product_rating_table extends Migration
{
    private $tableName = 'product_rating';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'product_variant_id' => $this->integer()->notNull(),
            'member_profile_id' => $this->integer()->notNull(),
            'rating' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'product_variant' => [],
                'member_profile' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'product_variant_id' => 1,
                'member_profile_id' => 1,
                'rating' => [
                    'score' => 5,
                    'review' => 'Great product, very cold and efficient.',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'product_variant_id' => 2,
                'member_profile_id' => 1,
                'rating' => [
                    'score' => 4,
                    'review' => 'Great product, very cold and efficient.',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 2,
                        'name' => 'Gree GWC-09F5S 1 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'product_variant_id' => 3,
                'member_profile_id' => 1,
                'rating' => [
                    'score' => 3,
                    'review' => 'Great product, very cold and efficient.',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 3,
                        'name' => 'Gree GWC-12F5S 1.5 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'product_variant_id' => 4,
                'member_profile_id' => 1,
                'rating' => [
                    'score' => 4,
                    'review' => 'Great product, very cold and efficient.',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 4,
                        'name' => 'Gree GWC-18F5S 2 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'product_variant_id' => 5,
                'member_profile_id' => 1,
                'rating' => [
                    'score' => 4,
                    'review' => 'Great product, very cold and efficient.',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 5,
                        'name' => 'Gree GWC-24F5S 2.5 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        foreach ($initialData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);

            #uncomment below code if you want to insert data to mongodb
            // $insertID['id'] = $key + 1;
            // $collection->insertOne(array_merge($insertID, $value));
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
