<?php

use yii\db\Migration;
use yii\db\Query;

class m251223_103400_create_product_variant_table extends Migration
{
    private $tableName = 'product_variant';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'stock' => $this->integer(),
            'product_id' => $this->integer()->notNull(),
            'variant_code' => $this->string(100)->notNull(),
            'sku' => $this->string(255)->notNull(),
            'image_url' => $this->json()->notNull()->defaultValue(json_encode([])),
            'detail_specs' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'product' => [],
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_product_variant_product_id', '{{%' . $this->tableName . '}}', 'product_id');
        $this->createIndex('uq_product_variant_code', '{{%' . $this->tableName . '}}', 'variant_code', true);
        $this->addForeignKey(
            'fk_product_variant_product',
            '{{%' . $this->tableName . '}}',
            'product_id',
            '{{%product}}',
            'id',
            'CASCADE',
            'CASCADE'
        );

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialVariants = [
            [
                'name' => 'Gree GWC-05F5S 0.5 PK',
                'sku' => '05F5S',
                'product_id' => 1,
                'stock' => 10,
                'image_url' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-05f5s_250.jpg?v20251103=',
                ],
                'detail_specs' => [
                    'power' => 0.5,
                    'cspf_rating' => 4,
                    'refrigerant' => 'R32',
                    'voltage' => [
                        'min' => 220,
                        'max' => 240,
                    ],
                    'application_area' => [
                        'min' => 5,
                        'max' => 7,
                    ],
                    'power_consumption' => [
                        'watt' => 350,
                        'range' => [
                            'min' => 190,
                            'max' => 630,
                        ],
                    ],
                    'cooling_capacity' => 5000,
                    'pipe_size' => [
                        'liquid' => '1/4',
                        'gas' => '3/8',
                    ],
                    'warranty' => [
                        'replacement' => 1,
                        'sparepart' => 5,
                        'compressor' => 10,
                        'type' => 'Official',
                    ],
                    'dimension'=> [
                        'indoor' => [
                            'width' => 704,
                            'height' => 260,
                            'length' => 185,
                            'weight' => null,
                        ],
                        'outdoor' => [
                            'width' => 710,
                            'height' => 450,
                            'length' => 293,
                            'weight' => null,
                        ],
                    ],
                ],
                'status' => 1,
                'change_log' => [
                    'product' => [
                        'id' => 1,
                        'name' => 'Gree F5S Series',
                    ],
                    'created_at' => $UTCTimestamp,
                    'created_by' => $dbDefault['createdBy'],
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ],
            [
                'name' => 'Gree GWC-09F5S 1 PK',
                'sku' => '09F5S',
                'product_id' => 1,
                'stock' => 10,
                'image_url' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-09f5s_250.jpg?v20251103=',
                ],
                'detail_specs' => [
                    'power' => 1,
                    'cspf_rating' => 5,
                    'refrigerant' => 'R32',
                    'voltage' => [
                        'min' => 220,
                        'max' => 240,
                    ],
                    'application_area' => [
                        'min' => 11,
                        'max' => 13,
                    ],
                    'power_consumption' => [
                        'watt' => 655,
                        'range' => [
                            'min' => 330,
                            'max' => 950,
                        ],
                    ],
                    'cooling_capacity' => 9000,
                    'pipe_size' => [
                        'liquid' => '1/4',
                        'gas' => '3/8',
                    ],
                    'warranty' => [
                        'replacement' => 1,
                        'sparepart' => 5,
                        'compressor' => 10,
                        'type' => 'Official',
                    ],
                    'dimension'=> [
                        'indoor' => [
                            'width' => 704,
                            'height' => 260,
                            'length' => 185,
                            'weight' => null,
                        ],
                        'outdoor' => [
                            'width' => 710,
                            'height' => 450,
                            'length' => 293,
                            'weight' => null,
                        ],
                    ],
                ],
                'status' => 1,
                'change_log' => [
                    'created_at' => $UTCTimestamp,
                    'created_by' => $dbDefault['createdBy'],
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ],
            [
                'name' => 'Gree GWC-12F5S 1.5 PK',
                'sku' => '12F5S',
                'product_id' => 1,
                'stock' => 10,
                'image_url' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-12f5s_250.jpg?v20251103=',
                ],
                'detail_specs' => [
                    'power' => 1.5,
                    'cspf_rating' => 5,
                    'refrigerant' => 'R32',
                    'voltage' => [
                        'min' => 220,
                        'max' => 240,
                    ],
                    'application_area' => [
                        'min' => 15,
                        'max' => 17,
                    ],
                    'power_consumption' => [
                        'watt' => 1170,
                        'range' => [
                            'min' => 320,
                            'max' => 1600,
                        ],
                    ],
                    'cooling_capacity' => 12100,
                    'pipe_size' => [
                        'liquid' => '1/4',
                        'gas' => '3/8',
                    ],
                    'warranty' => [
                        'replacement' => 1,
                        'sparepart' => 5,
                        'compressor' => 10,
                        'type' => 'Official',
                    ],
                    'dimension'=> [
                        'indoor' => [
                            'width' => 779,
                            'height' => 260,
                            'length' => 185,
                            'weight' => null,
                        ],
                        'outdoor' => [
                            'width' => 732,
                            'height' => 550,
                            'length' => 330,
                            'weight' => null,
                        ],
                    ],
                ],
                'status' => 1,
                'change_log' => [
                    'created_at' => $UTCTimestamp,
                    'created_by' => $dbDefault['createdBy'],
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ],
            [
                'name' => 'Gree GWC-18F5S 2 PK',
                'sku' => '18F5S',
                'product_id' => 1,
                'stock' => 10,
                'image_url' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-18f5s_250.jpg?v20251103=',
                ],
                'detail_specs' => [
                    'power' => 2,
                    'cspf_rating' => 5,
                    'refrigerant' => 'R32',
                    'voltage' => [
                        'min' => 220,
                        'max' => 240,
                    ],
                    'application_area' => [
                        'min' => 23,
                        'max' => 26,
                    ],
                    'power_consumption' => [
                        'watt' => 1500,
                        'range' => [
                            'min' => 300,
                            'max' => 1750,
                        ],
                    ],
                    'cooling_capacity' => 18000,
                    'pipe_size' => [
                        'liquid' => '1/4',
                        'gas' => '3/8',
                    ],
                    'warranty' => [
                        'replacement' => 1,
                        'sparepart' => 5,
                        'compressor' => 10,
                        'type' => 'Official',
                    ],
                    'dimension'=> [
                        'indoor' => [
                            'width' => 982,
                            'height' => 311,
                            'length' => 221,
                            'weight' => null,
                        ],
                        'outdoor' => [
                            'width' => 732,
                            'height' => 550,
                            'length' => 330,
                            'weight' => null,
                        ],
                    ],
                ],
                'status' => 1,
                'change_log' => [
                    'created_at' => $UTCTimestamp,
                    'created_by' => $dbDefault['createdBy'],
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ],
            [
                'name' => 'Gree GWC-24F5S 2.5 PK',
                'sku' => '24F5S',
                'product_id' => 1,
                'stock' => 10,
                'image_url' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-24f5s_250.jpg?v20251103=',
                ],
                'detail_specs' => [
                    'power' => 2.5,
                    'cspf_rating' => 5,
                    'refrigerant' => 'R32',
                    'voltage' => [
                        'min' => 220,
                        'max' => 240,
                    ],
                    'application_area' => [
                        'min' => 30,
                        'max' => 34,
                    ],
                    'power_consumption' => [
                        'watt' => 1920,
                        'range' => [
                            'min' => 450,
                            'max' => 2350,
                        ],
                    ],
                    'cooling_capacity' => 24000,
                    'pipe_size' => [
                        'liquid' => '1/4',
                        'gas' => '5/8',
                    ],
                    'warranty' => [
                        'replacement' => 1,
                        'sparepart' => 5,
                        'compressor' => 10,
                        'type' => 'Official',
                    ],
                    'dimension'=> [
                        'indoor' => [
                            'width' => 1081,
                            'height' => 325,
                            'length' => 248,
                            'weight' => null,
                        ],
                        'outdoor' => [
                            'width' => 873,
                            'height' => 555,
                            'length' => 367,
                            'weight' => null,
                        ],
                    ],
                ],
                'status' => 1,
                'change_log' => [
                    'created_at' => $UTCTimestamp,
                    'created_by' => $dbDefault['createdBy'],
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ],
        ];

        foreach ($initialVariants as $variant) {
            if (!isset($variant['product_id']) || !$variant['product_id']) {
                continue;
            }

            if (!isset($variant['variant_code']) || $variant['variant_code'] === null || $variant['variant_code'] === '') {
                $variant['variant_code'] = $variant['sku'] ?? null;
            }

            if (isset($variant['change_log'])) {
                $variant['detail_info'] = [
                    'change_log' => $variant['change_log'],
                ];
                unset($variant['change_log']);
            }

            $this->insert('{{%' . $this->tableName . '}}', $variant);
        }
    }

    public function safeDown()
    {
        $this->dropForeignKey('fk_product_variant_product', '{{%' . $this->tableName . '}}');
        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
