<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%pipe_package}}`.
 */
class m251229_055000_create_pipe_package_table extends Migration
{
    private $tableName = 'pipe_package';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'code' => $this->string(20)->notNull(),
            'name' => $this->string(255)->notNull(),
            'power_min' => $this->float()->notNull(),
            'power_max' => $this->float()->notNull(),
            'btu_min' => $this->integer()->notNull(),
            'btu_max' => $this->integer()->notNull(),
            'liquid_size' => $this->string(10)->notNull(),
            'gas_size' => $this->string(10)->notNull(),
            'price' => $this->float()->notNull()->defaultValue(0),
            'brand_id' => $this->integer()->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'brand' => null,
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('uq_installation_pipe_group_code', '{{%' . $this->tableName . '}}', 'code', true);

        $initialData = [
            [
                'name' => '0.5 - 1 PK (5.000 - 9.000 BTU)',
                'code' => 'PIPE_A',
                'power_min' => 0.5,
                'power_max' => 1.0,
                'btu_min' => 5000,
                'btu_max' => 9000,
                'liquid_size' => '1/4',
                'gas_size' => '3/8',
                'price' => 150000.00,
                'brand_id' => 5,
                'status' => 1,
                'detail_info' => [
                    'brand' => [
                        'id' => 5,
                        'name' => 'Hoda',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => '1.5 - 2 PK (12.000 - 18.000 BTU)',
                'code' => 'PIPE_B',
                'power_min' => 1.5,
                'power_max' => 2.0,
                'btu_min' => 12000,
                'btu_max' => 18000,
                'liquid_size' => '1/4',
                'gas_size' => '1/2',
                'price' => 250000.00,
                'status' => 1,
                'brand_id' => 5,
                'detail_info' => [
                    'change_log' => [
                        'brand' => [
                            'id' => 5,
                            'name' => 'Hoda',
                        ],
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => '2.5 PK (24.000 BTU)',
                'code' => 'PIPE_C',
                'power_min' => 2.5,
                'power_max' => 2.5,
                'btu_min' => 24000,
                'btu_max' => 24000,
                'liquid_size' => '3/8',
                'gas_size' => '5/8',
                'price' => 350000.00,
                'brand_id' => 5,
                'status' => 1,
                'detail_info' => [
                    'brand' => [
                        'id' => 5,
                        'name' => 'Hoda',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}