<?php

use yii\db\Migration;
// use MongoDB\Client;

/**
 * Handles the creation of table `{{%product}}`.
 */
class m251127_092659_create_product_table extends Migration
{
    private $tableName = 'product';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];
        
        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'description' => $this->string()->notNull(),
            'thumbnail' => $this->string(255)->notNull(),
            'images' => $this->json()->notNull()->defaultValue(json_encode([])),
            'category_id' => $this->integer()->notNull(),
            'product_type_id' => $this->integer()->notNull(),
            'service_category_id' => $this->integer()->notNull(),
            'brand_id' => $this->integer()->notNull(),
            'variant' => $this->json()->notNull()->defaultValue(json_encode([])),
            'badges' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'product_type' => [],
                    'category' => [],
                    'service_category' => [],
                    'brand' => [],
                    'dimension'=> [],
                    'badges' => [],
                    'seo_url' => null,
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
            // 'sync' => $this->smallInteger()->defaultValue(null)->comment('1: unsync, null: synced'),
            // uncomment this if u want use optimistic locking
            // 'lock_version' => $this->integer()->notNull()->defaultValue(1)->comment('Optimistic Locking'),
        ]);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialProducts = [
            [
                'name' => 'Gree F5S Series',
                'description' => 'AC Gree F5S Inverter Series',
                'thumbnail' => 'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-05f5s.jpg',
                'images' => [
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-05f5s.jpg?v20251128',
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-09f5s.jpg?v20251128',
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-12f5s.jpg?v20251128',
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-18f5s.jpg?v20251128',
                    'https://www.selka.id/assets/images/product/gree/ac-split/gree_gwc-24f5s.jpg?v20251128',
                ],
                'category_id' => 1,
                'product_type_id' => 3,
                'service_category_id' => 1,
                'brand_id' => 2,
                'badges' => [
                    'INVERTER',
                ],
                'status' => 1,
                'detail_info' => [
                    'product_type' => [
                        'id' => 3,
                        'name' => 'Split Wall - Inverter'
                    ],
                    'category' => [
                        'id' => 1,
                        'name' => 'AC Split Wall',
                    ],
                    'service_category' => [
                        'id' => 1,
                        'name' => 'Home AC',
                    ],
                    'brand' => [
                        'id' => 2,
                        'name' => 'Gree',
                    ],
                    'seo_url' => 'gree-f5s-series',
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        foreach ($initialProducts as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);

            #uncomment below code if you want to insert data to mongodb
            // $insertID['id'] = $key + 1;
            // $collection->insertOne(array_merge($insertID, $value));
        }

    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];
        
        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}



