<?php

use yii\db\Migration;

class m251213_160400_create_member_profile_table extends Migration
{
    private $tableName = 'member_profile';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'email' => $this->string(255)->defaultValue(null),
            'phone' => $this->json()->notNull()->defaultValue(json_encode([])),
            'avatar' => $this->string(255)->defaultValue(null),
            'gender' => $this->string(6)->defaultValue(null),
            'birth_date' => $this->date()->defaultValue(null),
            'detail_address' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'name' => 'John Doe',
                'email' => 'john.doe@example.com',
                'phone' => ['6281122223412'],
                'avatar' => 'https://enterkomputer.com/assets/img/ecomm/marketplace-placeholder.svg',
                'gender' => 'Male',
                'birth_date' => '1990-01-01',
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
