<?php

use yii\db\Migration;

class m251213_170000_create_voucher_table extends Migration
{
    private $tableName = 'voucher';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'code' => $this->string(50)->notNull(),
            'name' => $this->string(255)->notNull(),
            'description' => $this->string(255)->defaultValue(null),
            'type' => $this->string(10)->notNull(),
            'value' => $this->integer()->notNull()->defaultValue(0),
            'min_purchase' => $this->integer()->notNull()->defaultValue(0),
            'max_discount' => $this->integer()->notNull()->defaultValue(0),
            'quota' => $this->integer()->notNull()->defaultValue(0),
            'used' => $this->integer()->notNull()->defaultValue(0),
            'start_at' => $this->timestamp()->notNull(),
            'end_at' => $this->timestamp()->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx-voucher-code-unique', '{{%' . $this->tableName . '}}', 'code', true);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'code' => 'WELCOME10',
                'name' => 'Welcome Voucher 10%',
                'description' => 'Diskon 10% untuk pengguna baru',
                'type' => 'percent',
                'value' => 10,
                'min_purchase' => 100000,
                'max_discount' => 50000,
                'quota' => 1000,
                'used' => 0,
                'start_at' => $UTCTimestamp,
                'end_at' => gmdate($params['timestamp']['UTC'], strtotime('+30 day', strtotime($UTCTimestamp))),
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'FREESHIP20',
                'name' => 'Free Shipping 20K',
                'description' => 'Potongan ongkir 20.000',
                'type' => 'fixed',
                'value' => 20000,
                'min_purchase' => 50000,
                'max_discount' => 20000,
                'quota' => 500,
                'used' => 0,
                'start_at' => $UTCTimestamp,
                'end_at' => gmdate($params['timestamp']['UTC'], strtotime('+14 day', strtotime($UTCTimestamp))),
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
