<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%pipe_installation}}`.
 */
class m251229_055100_create_pipe_installation_table extends Migration
{
    private $tableName = 'pipe_installation';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'code' => $this->string(50)->notNull(),
            'name' => $this->string(255)->notNull(),
            'description' => $this->string()->null(),
            'length' => $this->float()->null(),
            'package_price' => $this->float()->notNull()->defaultValue(0),
            'included_items' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('uq_pipe_installation_code', '{{%' . $this->tableName . '}}', 'code', true);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'code' => 'INSTALL_3M',
                'name' => 'Paket Pemasangan 3 Meter',
                'description' => 'Jasa instalasi + material standar 3 meter.',
                'length' => 3,
                'package_price' => 150000.00,
                'included_items' => [
                    [
                        'label' => 'Jasa Instalasi',
                        'note' => null,
                    ],
                    [
                        'label' => 'Kabel Control Supreme',
                        'note' => '2.5mm, 4 Meter',
                    ],
                    [
                        'label' => 'Selang Air Flexible',
                        'note' => '2 Meter',
                    ],
                    [
                        'label' => 'Bracket Outdoor',
                        'note' => null,
                    ],
                    [
                        'label' => 'Duct Tape',
                        'note' => null,
                    ],
                    [
                        'label' => 'Free Vaccum Unit',
                        'note' => null,
                    ],
                    [
                        'label' => 'Free Bobok 1 Titik',
                        'note' => null,
                    ],
                ],
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'INSTALL_5M',
                'name' => 'Paket Pemasangan 5 Meter',
                'description' => 'Jasa instalasi + material standar 5 meter.',
                'length' => 5,
                'package_price' => 300000.00,
                'included_items' => [
                    [
                        'label' => 'Jasa Instalasi',
                        'note' => null,
                    ],
                    [
                        'label' => 'Kabel Control Supreme',
                        'note' => '2.5mm, 6 Meter',
                    ],
                    [
                        'label' => 'Selang Air Flexible',
                        'note' => '2 Meter',
                    ],
                    [
                        'label' => 'Bracket Outdoor',
                        'note' => null,
                    ],
                    [
                        'label' => 'Duct Tape',
                        'note' => null,
                    ],
                    [
                        'label' => 'Free Vaccum Unit',
                        'note' => null,
                    ],
                    [
                        'label' => 'Free Bobok 1 Titik',
                        'note' => null,
                    ],
                ],
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'INSTALL_CUSTOM',
                'name' => 'Custom Paket Pemasangan',
                'description' => 'Jasa instalasi + material sesuai kebutuhan (panjang dihitung di POS).',
                'length' => null,
                'package_price' => 0,
                'included_items' => [
                    [
                        'label' => 'Jasa Instalasi',
                        'note' => null,
                    ],
                    [
                        'label' => 'Material',
                        'note' => 'Sesuai kebutuhan',
                    ],
                ],
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}