<?php

use yii\db\Migration;
// use MongoDB\Client;

/**
 * Handles the creation of table `{{%category}}`.
 */
class m251128_114600_create_category_table extends Migration
{
    private $tableName = 'category';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'image' => $this->string(255)->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'name' => 'AC Split Wall',
                'image' => 'https://aquaelektronik.com/upload_files/1/56445b50c2-ac-split.png',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'AC Multi Split Wall',
                'image' => 'https://www.hitachiaircon.com/storage/images/products/thumbs_952x743/product_image_grid_19132b3e1a51d11d21fec5b81225fe16.jpg',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'AC Portable',
                'image' => 'https://bintangplasma.com/wp-content/uploads/2024/08/ac-portable.jpg',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'AC Ceiling',
                'image' => 'https://s3.ap-southeast-3.amazonaws.com/hartono-mh1/images/detailed/384/FCFC71DVM4_1PH_WL-1.jpg',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Air Cooler',
                'image' => 'https://media.monotaro.id/mid01/big/Alat%20AC%20%26%20Pipa/Penyejuk%20Udara%2C%20Ventilasi/Alat%20Pendingin%20Industri/Sharp%20Air%20Cooler%20(Pendingin%20Udara)/P102171578-1.jpg',
                'status' => 1,
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        foreach ($initialData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);

            #uncomment below code if you want to insert data to mongodb
            // $insertID['id'] = $key + 1;
            // $collection->insertOne(array_merge($insertID, $value));
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        #uncomment below code if you want to insert data to mongodb
        // $mongodb = new Client($mongodb_param['dsn']);
        // $collection = $mongodb->selectCollection($mongodb_param['database'], $this->tableName);
        // $collection->drop();

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
