<?php

use yii\db\Migration;
use app\helpers\Constants;

class m260125_140000_create_product_order_table extends Migration
{
    private $tableName = 'product_order';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_profile_id' => $this->integer()->notNull(),
            'items' => $this->json()->notNull()->defaultValue(json_encode([])),
            'detail_address' => $this->json()->notNull()->defaultValue(json_encode([])),
            'pricing_summary' => $this->json()->notNull()->defaultValue(json_encode([])),
            'note' => $this->text()->null(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
            'sync_mdb' => $this->smallInteger()->defaultValue(null)->comment($dbDefault['syncMdbComment']),
            'lock_version' => $this->integer()->notNull()->defaultValue($dbDefault['lockVersion'])->comment($dbDefault['optimisticLockingComment']),
        ]);

        $this->createIndex('idx_product_order_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');

        $dummyData = [
            [
                'member_profile_id' => 1,
                'items' => [
                    [
                        'product_variant_id' => 5,
                        'name' => 'Gree GWC-24F5S 2.5 PK',
                        'sku' => '24F5S',
                        'qty' => 1,
                        'original_price' => 10779000.00,
                        'price' => 9979000.00,
                    ],
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'pricing_summary' => [
                    'currency' => $dbDefault['currency'] ?? 'IDR',
                    'subtotal' => 9979000.00,
                    'discount' => 0,
                    'shipping' => 0,
                    'grand_total' => 9979000.00,
                ],
                'note' => null,
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($dummyData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
