<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%cleaning_order}}`.
 */
class m260122_094108_create_cleaning_order_table extends Migration
{
    private $tableName = 'cleaning_order';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_profile_id' => $this->integer()->notNull(),
            'service_type_id' => $this->integer()->notNull(),
            'product_variant_id' => $this->integer()->notNull(),
            'category_id' => $this->integer()->notNull(),
            'cleaning_type_id' => $this->integer()->notNull(),
            'ac_condition' => $this->json()->notNull()->defaultValue(json_encode([])),
            'ac_desciption' => $this->text()->null(),
            'qty' => $this->integer()->notNull()->defaultValue(1),
            'pricing' => $this->json()->notNull()->defaultValue(json_encode([])),
            'detail_address' => $this->json()->notNull()->defaultValue(json_encode([])),
            'schedule' => $this->json()->notNull()->defaultValue(json_encode([])),
            'note' => $this->text()->null(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'product_variant' => [],
                'cleaning_type' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_cleaning_order_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'member_profile_id' => 1,
                'service_type_id' => 1,
                'product_variant_id' => 1,
                'category_id' => 1,
                'cleaning_type_id' => 1,
                'ac_condition' => [
                    [
                        'id' => 1,
                        'name' => 'Kurang Dingin',
                    ],
                    [
                        'id' => 2,
                        'name' => 'Bocor',
                    ],
                    [
                        'id' => 3,
                        'name' => 'Bau',
                    ],
                    [
                        'id' => 4,
                        'name' => 'Rutin Cuci',
                    ],
                ],
                'ac_desciption' => 'Lorem Ipsum',
                'qty' => 1,
                'pricing' => [
                    'cleaning_type_price' => 150000,
                    'total_per_unit' => 150000,
                    'grand_total' => 150000,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'schedule' => [
                    'date' => '2026-01-24',
                    'time' => 'Siang (12:00-16:00)',
                ],
                'note' => 'Lorem Ipsum',
                'status' => 1,
                'detail_info' => [
                    'member_profile_id' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'category' => [
                        'id' => 1,
                        'name' => 'AC Split Wall',
                    ],
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                        'brand' => [
                            'id' => 2,
                            'name' => 'Gree',
                        ],
                    ],
                    'cleaning_type' => [
                        'id'=> 1,
                        'name'=> 'Normal Cleaning',
                        'base_price'=> 150000,
                    ],
                    'service_type' => [
                        'id' => 3,
                        'name' => 'Cleaning',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
