<?php

use yii\db\Migration;

class m260119_163000_create_service_checkout_preview_table extends Migration
{
    private $tableName = 'service_checkout_preview';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_id' => $this->integer()->notNull(),
            'client_uuid' => $this->string(64)->null(),
            'service_type' => $this->string(50)->notNull()->defaultValue('installation'),
            'installation_package_id' => $this->integer()->null(),
            'installation_package_code' => $this->string(50)->null(),
            'pipe_grade_id' => $this->integer()->null(),
            'length' => $this->float()->null(),
            'qty' => $this->integer()->notNull()->defaultValue(1),
            'pricing' => $this->json()->notNull()->defaultValue(json_encode([])),
            'payload' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_member_checkout_quote_member_id', '{{%' . $this->tableName . '}}', 'member_id');
        $this->createIndex('idx_member_checkout_quote_client_uuid', '{{%' . $this->tableName . '}}', 'client_uuid');
        $this->createIndex('idx_member_checkout_quote_status', '{{%' . $this->tableName . '}}', 'status');

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
