<?php

use yii\db\Migration;

class m260119_163000_create_service_order_table extends Migration
{
    private $tableName = 'service_order';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_id' => $this->integer()->notNull(),
            'client_uuid' => $this->string(64)->null(),
            'service_type' => $this->integer()->notNull()->defaultValue(1),
            'product_variant_id' => $this->integer()->null(),
            'installation_package_id' => $this->integer()->null(),
            'installation_service' => $this->json()->defaultValue(json_encode([])),
            'cleaning_type_id' => $this->integer()->null(),
            'pipe_grade_id' => $this->integer()->null(),
            'length' => $this->float()->null(),
            'qty' => $this->integer()->notNull()->defaultValue(1),
            'pricing' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'product_variant' => [],
                'installation_package' => [],
                'cleaning_type' => [],
                'pipe_grade' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_member_order_quote_member_id', '{{%' . $this->tableName . '}}', 'member_id');
        $this->createIndex('idx_member_order_quote_client_uuid', '{{%' . $this->tableName . '}}', 'client_uuid');
        $this->createIndex('idx_member_order_quote_status', '{{%' . $this->tableName . '}}', 'status');
        $this->createIndex('idx_member_order_quote_installation_package_id', '{{%' . $this->tableName . '}}', 'installation_package_id');
        $this->createIndex('idx_member_order_quote_cleaning_type_id', '{{%' . $this->tableName . '}}', 'cleaning_type_id');

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'member_id' => 1,
                'service_type' => 1,
                'product_variant_id' => 1,
                'installation_package_id' => null,
                'installation_service' => [],
                'cleaning_type_id' => null,
                'pipe_grade_id' => 1,
                'length' => 3,
                'qty' => 1,
                'pricing' => [
                    'base_price' => 150000,
                    'price_per_meter' => 75000,
                    'pipe_price' => 225000,
                    'total_per_unit' => 225000,
                    'grand_total' => 225000,
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                    ],
                    'installation_package' => [
                        'id' => 1,
                        'code' => 'INSTALL_3M',
                        'name' => 'Paket Pemasangan 3 Meter',
                        'base_price' => 150000,
                    ],
                    'cleaning_type' => [],
                    'pipe_grade' => [
                        'id'=> 1,
                        'name'=> 'Premium',
                        'thickness_mm'=> 0.6,
                        'brand' => [
                            'id'=> 5,
                            'name'=> 'Hoda',
                        ],
                        'price_per_meter'=> 75000,
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'member_id' => 1,
                'service_type' => 1,
                'product_variant_id' => 1,
                'installation_package_id' => null,
                'installation_service' => [
                    [
                        'id' => 1,
                        'code' => "INSTALL_SERVICE_AC_NEW",
                        'name' => "Jasa Pasang AC Baru",
                        'unit_type' => "unit",
                        'base_price' => 350000,
                        'qty' => 1,
                        'subtotal' => 350000,
                    ],
                    [
                        'id' => 2,
                        'code' => "INSTALL_MATERIAL_PIPE",
                        'name' => "Pipa AC",
                        'unit_type' => "meter",
                        'base_price' => 45000,
                        'qty' => 2,
                        'subtotal' => 270000,
                    ],
                ],
                'cleaning_type_id' => null,
                'pipe_grade_id' => null,
                'length' => 3,
                'qty' => 1,
                'pricing' => [
                    'base_price' => 620000,
                    'price_per_meter' => 0,
                    'pipe_price' => 0,
                    'total_per_unit' => 620000,
                    'grand_total' => 620000,
                ],
                'status' => 1,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                    ],
                    'installation_package' => [],
                    'cleaning_type' => [],
                    'pipe_grade' => [],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
