<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%unit_condition}}`.
 */
class m260113_140000_create_unit_condition_table extends Migration
{
    private $tableName = 'unit_condition';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(100)->notNull()->unique(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $initialData = [
            [
                'name' => 'Kurang Dingin',
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => null,
                        'created_by' => null,
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Bocor',
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Bau',
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Rutin Cuci',
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
