<?php

use yii\db\Migration;
use app\helpers\Constants;

class m260126_134500_create_cart_table extends Migration
{
    private $tableName = 'cart';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_profile_id' => $this->integer()->notNull(),
            'items' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'member_profile' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_cart_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');

        $dummyData = [
            [
                'member_profile_id' => 1,
                'items' => [
                    [
                        'item_type' => 'product',
                        'product_order_id' => 1,
                        'name' => 'Product Order Draft',
                        'product_order' => [
                            'id' => 1,
                            'product_variant_id' => 5,
                            'name' => 'Gree GWC-24F5S 2.5 PK',
                            'sku' => '24F5S',
                        ],
                        'qty' => 1,
                        'pricing_summary' => [
                            'subtotal' => 1899000,
                            'grand_total' => 1899000,
                        ],
                        'note' => null,
                    ],
                    [
                        'item_type' => 'installation',
                        'installation_order_id' => 1,
                        'service_type' => [
                            'id' => 1,
                            'name' => 'Installation Package',
                        ],
                        'installation_package' => [
                            'id' => 1,
                            'code' => 'INSTALL_3M',
                            'name' => 'Paket Pemasangan 3 Meter',
                        ],
                        'pipe_grade' => [
                            'id'=> 1,
                            'name'=> 'Premium',
                        ],
                        'schedule' => [
                            'date' => '2026-10-01',
                            'time_slot' => 'Siang (12:00 - 16:00)',
                        ],
                        'detail_address' => [
                            'city' => 'Jakarta Selatan',
                            'district' => 'Tebet',
                            'sub_district' => 'Tebet Barat',
                            'zip_code' => '12810',
                            'location' => [
                                'lat' => -6.235000,
                                'lng' => 106.850000,
                            ],
                        ],
                        'pricing_summary' => [
                            'subtotal' => 375000,
                            'grand_total' => 375000,
                        ],
                        'qty' => 1,
                        'note' => null,
                    ],
                    [
                        'item_type' => 'cleaning',
                        'cleaning_order_id' => 1,
                        'service_type' => [
                            'id' => 3,
                            'name' => 'Cleaning',
                        ],
                        'category' => [
                            'id' => 1,
                            'name' => 'AC Split Wall',
                        ],
                        'cleaning_type' => [
                            'id'=> 1,
                            'name'=> 'Normal Cleaning',
                        ],
                        'schedule' => [
                            'date' => '2026-11-07',
                            'time_slot' => 'Pagi (08:00 - 12:00)',
                        ],
                        'detail_address' => [
                            'city' => 'Jakarta Selatan',
                            'district' => 'Tebet',
                            'sub_district' => 'Tebet Barat',
                            'zip_code' => '12810',
                            'location' => [
                                'lat' => -6.235000,
                                'lng' => 106.850000,
                            ],
                        ],
                        'pricing_summary' => [
                            'subtotal' => 150000,
                            'grand_total' => 150000,
                        ],
                        'qty' => 1,
                        'note' => null,
                    ],
                ],
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($dummyData as $value) {
            // $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
