<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%wishlist}}`.
 */
class m260127_163700_create_wishlist_table extends Migration
{
    private $tableName = 'wishlist';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'product_variant_id' => $this->integer()->notNull(),
            'member_profile_id' => $this->integer()->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'product_variant' => [],
                'member_profile' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_wishlist_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');
        $this->createIndex('idx_wishlist_product_variant_id', '{{%' . $this->tableName . '}}', 'product_variant_id');

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'product_variant_id' => 1,
                'member_profile_id' => 1,
                'status' => 2,
                'detail_info' => [
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                    ],
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
