<?php

use yii\db\Migration;

class m260128_170500_create_checkout_table extends Migration
{
    private $tableName = 'checkout';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_profile_id' => $this->integer()->notNull(),
            'cart_snapshot' => $this->json()->notNull()->defaultValue(json_encode([])),
            'pricing' => $this->json()->notNull()->defaultValue(json_encode([])),
            'voucher_code' => $this->string(50)->defaultValue(null),
            'payment_method' => $this->string(50)->notNull()->defaultValue('BANK_TRANSFER_BCA'),
            'payment_detail' => $this->json()->notNull()->defaultValue(json_encode([])),
            'payment_status' => $this->string(30)->notNull()->defaultValue('WAITING_PAYMENT'),
            'expired_at' => $this->timestamp()->null(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['statusService'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_checkout_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');
        $this->createIndex('idx_checkout_payment_status', '{{%' . $this->tableName . '}}', 'payment_status');

        $dummyData = [
            [
                'member_profile_id' => 1,
                'cart_snapshot' => [
                    'items' => [],
                ],
                'pricing' => [
                    'items_subtotal' => 0,
                    'service_subtotal' => 0,
                    'shipping_cost' => 0,
                    'discount' => 0,
                    'grand_total' => 0,
                ],
                'voucher_code' => null,
                'payment_method' => 'BANK_TRANSFER_BCA',
                'payment_detail' => [
                    'bank' => 'BCA',
                    'account_number' => '1234567890',
                    'account_name' => 'CV Elektro Techindo Horizon',
                    'amount' => 0,
                ],
                'payment_status' => 'WAITING_PAYMENT',
                'expired_at' => $UTCTimestamp,
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,  
                        'created_by' => $dbDefault['createdBy'],               
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($dummyData as $value) {
            // $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
