<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%installation_service}}`.
 */
class m260115_090000_create_installation_service_table extends Migration
{
    private $tableName = 'installation_service';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'code' => $this->string(50)->notNull()->unique(),
            'name' => $this->string(255)->notNull(),
            'description' => $this->text()->null(),
            'service_type' => $this->string(50)->notNull()->comment('non_package'),
            'unit_type' => $this->string(50)->notNull()->defaultValue('unit')->comment('unit or meter'),
            'base_price' => $this->float()->notNull()->defaultValue(0),
            'estimated_duration' => $this->integer()->null()->comment('Duration in minutes'),
            'detail_service' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $initialData = [
            [
                'code' => 'INSTALL_SERVICE_AC_NEW',
                'name' => 'Jasa Pasang AC Baru',
                'description' => 'Belum termasuk material, sudah termasuk vakum. Pembelian tanpa paket tidak mendapatkan garansi 30 hari pemasangan.',
                'service_type' => 'non_package',
                'unit_type' => 'unit',
                'base_price' => 350000,
                'estimated_duration' => 90,
                'detail_service' => [
                    'recommended_for' => 'Jasa pemasangan saja (material disediakan customer)',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'INSTALL_MATERIAL_PIPE',
                'name' => 'Pipa AC',
                'description' => 'Pipa tembaga AC sambungan dari indoor ke outdoor untuk aliran freon. Jika panjang pipa lebih dari 5m maka harus membeli jasa tarik pipa dibawah ini.',
                'service_type' => 'non_package',
                'unit_type' => 'meter',
                'base_price' => 45000,
                'estimated_duration' => null,
                'detail_service' => [
                    'recommended_for' => 'Pembelian pipa per meter',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'INSTALL_SERVICE_PULL_PIPE',
                'name' => 'Jasa Tarik Pipa',
                'description' => 'Dikenakan jika panjang pipa > 5m per AC, atau menggunakan material pipa dari konsumen.',
                'service_type' => 'non_package',
                'unit_type' => 'unit',
                'base_price' => 150000,
                'estimated_duration' => 60,
                'detail_service' => [
                    'recommended_for' => 'Jasa penarikan pipa untuk instalasi',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'code' => 'INSTALL_MATERIAL_CABLE_3',
                'name' => 'Kabel AC Isi 3',
                'description' => 'Untuk kebutuhan kabel isi 4 khusus AC Inverter, silahkan menghubungi kami atau langsung penambahan ke teknisi.',
                'service_type' => 'non_package',
                'unit_type' => 'unit',
                'base_price' => 75000,
                'estimated_duration' => null,
                'detail_service' => [
                    'recommended_for' => 'Pembelian kabel AC 3 core',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
