<?php

use yii\db\Migration;

class m260119_163000_create_installation_order_table extends Migration
{
    private $tableName = 'installation_order';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'member_profile_id' => $this->integer()->notNull(),
            'service_type_id' => $this->integer()->notNull()->defaultValue(1),
            'product_variant_id' => $this->integer()->null(),
            'installation_package_id' => $this->integer()->null(),
            'installation_service' => $this->json()->defaultValue(json_encode([])),
            'pipe_grade_id' => $this->integer()->null(),
            'length' => $this->float()->null(),
            'qty' => $this->integer()->notNull()->defaultValue(1),
            'pricing' => $this->json()->notNull()->defaultValue(json_encode([])),
            'detail_address' => $this->json()->notNull()->defaultValue(json_encode([])),
            'schedule' => $this->json()->notNull()->defaultValue(json_encode([])),
            'note' => $this->text()->null(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'product_variant' => [],
                'installation_package' => [],
                'pipe_grade' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $this->createIndex('idx_member_order_quote_member_profile_id', '{{%' . $this->tableName . '}}', 'member_profile_id');
        $this->createIndex('idx_member_order_quote_installation_package_id', '{{%' . $this->tableName . '}}', 'installation_package_id');

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'member_profile_id' => 1,
                'service_type_id' => 1,
                'product_variant_id' => 1,
                'installation_package_id' => null,
                'installation_service' => [],
                'pipe_grade_id' => 1,
                'length' => 3,
                'qty' => 1,
                'pricing' => [
                    'installation_service_price' => 0,
                    'installation_package_price' => 150000,
                    'pipe_grade_price' => 225000,
                    'total_per_unit' => 375000,
                    'grand_total' => 375000,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'schedule' => [
                    'date' => '2026-01-24',
                    'time' => 'Siang (12:00-16:00)',
                ],
                'note' => 'Lorem Ipsum',
                'status' => 1,
                'detail_info' => [
                    'member_profile_id' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                        'brand' => [
                            'id' => 2,
                            'name' => 'Gree',
                        ],
                    ],
                    'installation_package' => [
                        'id' => 1,
                        'code' => 'INSTALL_3M',
                        'name' => 'Paket Pemasangan 3 Meter',
                        'base_price' => 150000,
                    ],
                    'pipe_grade' => [
                        'id'=> 1,
                        'name'=> 'Premium',
                        'thickness_mm'=> 0.6,
                        'brand' => [
                            'id'=> 5,
                            'name'=> 'Hoda',
                        ],
                        'price_per_meter'=> 75000,
                    ],
                    'service_type' => [
                        'id' => 1,
                        'name' => 'Installation Package',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'member_profile_id' => 1,
                'service_type_id' => 2,
                'product_variant_id' => 1,
                'installation_package_id' => null,
                'installation_service' => [
                    [
                        'id' => 1,
                        'code' => 'INSTALL_SERVICE_AC_NEW',
                        'name' => 'Jasa Pasang AC Baru',
                        'unit_type' => 'unit',
                        'base_price' => 350000,
                        'qty' => 1,
                        'subtotal' => 350000,
                    ],
                    [
                        'id' => 2,
                        'code' => 'INSTALL_MATERIAL_PIPE',
                        'name' => 'Pipa AC',
                        'unit_type' => 'meter',
                        'base_price' => 45000,
                        'qty' => 2,
                        'subtotal' => 270000,
                    ],
                ],
                'pipe_grade_id' => null,
                'length' => 3,
                'qty' => 1,
                'pricing' => [
                    'installation_service_price' => 620000,
                    'installation_package_price' => 0,
                    'pipe_grade_price' => 0,
                    'total_per_unit' => 620000,
                    'grand_total' => 620000,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'schedule' => [
                    'date' => '2026-01-24',
                    'time' => 'Pagi (08:00-12:00)',
                ],
                'note' => 'Lorem Ipsum',
                'status' => 1,
                'detail_info' => [
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                        'brand' => [
                            'id' => 2,
                            'name' => 'Gree',
                        ],
                    ],
                    'installation_package' => [],
                    'pipe_grade' => [],
                    'service_type' => [
                        'id' => 2,
                        'name' => 'Non Package Installation',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'member_profile_id' => 1,
                'service_type_id' => 1,
                'product_variant_id' => 1,
                'installation_package_id' => 2,
                'installation_service' => [
                    [
                        'id' => 4,
                        'code' => "INSTALL_MATERIAL_CABLE_3",
                        'name' => "Kabel AC Isi 3",
                        'unit_type' => "unit",
                        'base_price' => 75000,
                        'qty' => 1,
                        'subtotal' => 75000,
                    ],
                ],
                'pipe_grade_id' => 2,
                'length' => 5,
                'qty' => 1,
                'pricing' => [
                    'installation_service_price' => 75000,
                    'installation_package_price' => 300000,
                    'pipe_grade_price' => 450000,
                    'total_per_unit' => 825000,
                    'grand_total' => 825000,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'schedule' => [
                    'date' => '2026-01-24',
                    'time' => '12:00-16:00',
                ],
                'note' => 'Lorem Ipsum',
                'status' => 1,
                'detail_info' => [
                    'member_profile' => [
                        'id' => 1,
                        'name' => 'John Doe',
                        'email' => 'john.doe@example.com',
                        'phone' => ['6281122223412'],
                    ],
                    'product_variant' => [
                        'id' => 1,
                        'name' => 'Gree GWC-05F5S 0.5 PK',
                        'sku' => '05F5S',
                        'variant_code' => null,
                        'product' => [
                            'id' => 1,
                            'name' => 'Gree GWC-05F5S',
                        ],
                    ],
                    'installation_package' => [
                        'id' => 2,
                        'code' => 'INSTALL_5M',
                        'name' => 'Paket Pemasangan 5 Meter',
                        'base_price' => 300000,
                    ],
                    'pipe_grade' => [
                        'id'=> 2,
                        'name'=> 'Luxury',
                        'thickness_mm'=> 0.8,
                        'brand' => [
                            'id'=> 6,
                            'name'=> 'Saeki',
                        ],
                        'price_per_meter'=> 90000,
                    ],
                    'service_type' => [
                        'id' => 1,
                        'name' => 'Installation Package',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $key => $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
