<?php

use yii\db\Migration;
use yii\helpers\ArrayHelper;

class m260113_130700_create_pipe_grade_table extends Migration
{
    private $tableName = 'pipe_grade';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'brand_id' => $this->integer()->null(),
            'thickness_mm' => $this->float()->notNull(),
            'price_per_meter' => $this->decimal(10, 2)->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $initialData = [
            [
                'name' => 'Premium',
                'brand_id' => 5,
                'thickness_mm' => 0.6,
                'price_per_meter' => 75000.00,
                'status' => 1,
                'detail_info' => [
                    'brand' => [
                        'id' => 5,
                        'name' => 'Hoda',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Luxury',
                'brand_id' => 6,
                'thickness_mm' => 0.8,
                'price_per_meter' => 90000.00,
                'status' => 1,
                'detail_info' => [
                    'brand' => [
                        'id' => 6,
                        'name' => 'Saeki',
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
