<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%cleaning_type}}`.
 */
class m260113_140000_create_cleaning_type_table extends Migration
{
    private $tableName = 'cleaning_type';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(100)->notNull()->unique(),
            'description' => $this->text()->null(),
            'base_price' => $this->float()->notNull()->defaultValue(0),
            'estimated_duration' => $this->integer()->null()->comment('Duration in minutes'),
            'detail_service' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $initialData = [
            [
                'name' => 'Normal Cleaning',
                'description' => 'Cuci AC standar dengan pembersihan evaporator, blower, dan filter',
                'base_price' => 150000,
                'estimated_duration' => 60,
                'detail_service' => [
                    'services' => [
                        'Pembersihan filter udara',
                        'Pembersihan evaporator dengan chemical khusus',
                        'Pembersihan blower fan',
                        'Pembersihan drainase',
                        'Pemeriksaan tekanan freon',
                    ],
                    'includes' => [
                        'Chemical pembersih',
                        'Pengecekan kondisi AC',
                        'Test fungsionalitas',
                    ],
                    'excludes' => [
                        'Penambahan freon',
                        'Spare part replacement',
                        'Perbaikan kerusakan',
                    ],
                    'recommended_for' => 'AC yang digunakan rutin 2-3 bulan terakhir',
                ],
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => null,
                        'created_by' => null,
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'General Cleaning',
                'description' => 'Cuci AC lengkap dengan pembongkaran unit indoor untuk pembersihan maksimal',
                'base_price' => 250000.00,
                'estimated_duration' => 90,
                'detail_service' => [
                    'services' => [
                        'Pembongkaran unit indoor',
                        'Pembersihan evaporator dengan steam cleaning',
                        'Pembersihan blower fan secara menyeluruh',
                        'Pembersihan filter udara dengan chemical',
                        'Pembersihan drainase dan pipa pembuangan',
                        'Pembersihan casing indoor dan outdoor',
                        'Pemeriksaan kompresor dan kelistrikan',
                        'Kalibrasi thermostat',
                    ],
                    'includes' => [
                        'Chemical pembersih premium',
                        'Steam cleaning equipment',
                        'Pengecekan lengkap sistem',
                        'Test fungsionalitas menyeluruh',
                        'Garansi 30 hari untuk hasil pembersihan',
                    ],
                    'excludes' => [
                        'Penambahan freon (biaya tambahan)',
                        'Spare part replacement',
                        'Perbaikan kerusakan komponen',
                    ],
                    'recommended_for' => 'AC yang jarang dibersihkan (>6 bulan) atau mengalami masalah kinerja',
                ],
                'status' => $dbDefault['statusService'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
